volumes:
  prometheus-data:
    driver: local
  prometheus-config:
    driver: local
  grafana_data:
services:
  prediction-server:
    build: .
    image: accidentpredictionservice:1.0.0
    container_name: prediction
    ports:
      - "3000:3000"
    networks:
      - frontend-nw
    command: uvicorn src.api.app:app --host 0.0.0.0 --port 8000
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - prometheus-config:/etc/prometheus
      - prometheus-data:/prometheus
    restart: unless-stopped
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    networks:
        frontend-nw:
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3001:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - frontend-nw
  
networks:
  frontend-nw:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: br-toolsfe
